config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [:index, :show, :new, :create, :destroy] do
    resources :reviews, only: [:new, :create]
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
  resources :reviews, only: [:destroy]
  root to: 'cocktails#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  mount_uploader :photo, PhotoUploader

  def self.search(search)
    where("name ILIKE ?", "%#{search}%")
  end
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :content, presence: true
  validates :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :find_cocktail, only: [:show, :destroy]
  def index
    @cocktails = Cocktail.all
    if params[:search]
      @cocktails = Cocktail.search(params[:search]).order("created_at DESC")
    else
      @cocktails = Cocktail.all.order("created_at DESC")
    end
  end

  def show
    @dose = Dose.new
    @doses = @cocktail.doses
    @review = Review.new
    @reviews = @cocktail.reviews
    amount = 0
    sum = 0
    @cocktail.reviews.each do |review|
      sum += review.rating.to_i
    end
    @cocktail.reviews.each do
      amount += 1
    end
      @average_rating = sum.to_f / amount unless amount.zero?
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    @cocktail.save ? (redirect_to cocktail_path(@cocktail)) : (render :new)
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end

  def find_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :find_cocktail, only: [:create]
  def new
    @cocktail = find_cocktail
    @ingredients = Ingredient.all
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    @dose.save
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

  def find_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_cocktail, only: [:create]
  def new
    @cocktail = find_cocktail
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.cocktail = @cocktail
    @review.save
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to cocktail_path(@review.cocktail)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def find_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: url('https://images.pexels.com/photos/1260705/pexels-photo-1260705.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260');">
</div>
<div class="container text-center">
  <% if @cocktails.count > 0 %>
    <h1>All Cocktails (<%= @cocktails.count %>)</h1>
  <% end %>
  <div class="row">
    <% if @cocktails.blank? %>
    <br><br>
      <p>There are no recipes containing the term "<%= params[:search] %>".</p>
    <% end %>
    <% @cocktails.each do |cocktail| %>
      <div class="col-xs-12 col-sm-4">
        <div class="card zoom" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path cocktail.photo? ? cocktail.photo : "cocktail.png", height: 300, width: 400, crop: :fill %>');">
            <%= link_to "", cocktail_path(cocktail), :class => "card-link" %>
          <div>
            <h2><%= link_to cocktail.name, cocktail_path(cocktail) %></h2>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="row">
      <h1 class="text-center">New Cocktail</h1>
    <div class="col-sm-6 col-sm-offset-3">
      <%= simple_form_for [ @cocktail ], html: { class: "show-form" } do |f| %>
        <%= f.input :name %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.submit "Add Cocktail", class: "btn btn-danger", id: "sweet-alert-demo" %>
      <% end %>
      <%= link_to 'Back', cocktails_path %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="drinks" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= cl_image_path @cocktail.photo? ? @cocktail.photo : "cocktail.png"; %>');">
  <h1><%= @cocktail.name %></h1>
  <div class="rating-title">
    <% unless @average_rating == nil %>
      <strong><%= @average_rating.round(1) %></strong>
      <% case @average_rating.to_i %>
      <% when 1 %>
        <i class="fas fa-star stars"></i>
      <% when 2 %>
        <i class="fas fa-star stars"></i><i class="fas fa-star stars"></i>
      <% when 3 %>
        <i class="fas fa-star stars"></i><i class="fas fa-star stars"></i><i class="fas fa-star stars"></i>
      <% when 4 %>
        <i class="fas fa-star stars"></i><i class="fas fa-star stars"></i><i class="fas fa-star stars"></i><i class="fas fa-star stars"></i>
      <% when 5 %>
        <i class="fas fa-star stars"></i><i class="fas fa-star stars"></i><i class="fas fa-star stars"></i><i class="fas fa-star stars"></i><i class="fas fa-star stars"></i>
      <% end %>
    <% end %>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="links">
      <div class="back">
        <i class="fas fa-undo-alt"></i>
        <%= link_to 'Back', cocktails_path %>
      </div>
    </div>
      <hr>
    <div class="col-sm-4 col-sm-offset-1">
      <ul class="list-unstyled">
        <li><strong>Ingredients</strong>
        (<%= @doses.length %>)
        </li>
        <hr>
        <% @doses.each do |dose| %>
          <li>
            <%= link_to dose_path(dose) , method: "delete", id: "delete" do %>
            <i class="far fa-trash-alt"></i>
            <% end %> | <%= dose.description %> - <%= dose.ingredient.name %>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="col-sm-4 col-sm-offset-1">
      <ul class="list-unstyled">
        <li class="review-title">
          <strong>Add Ingredient</strong>
        </li>
        <hr>
        <%= simple_form_for [ @cocktail, @dose ], html: { class: "show-form" } do |f| %>
          <%= f.input :description %>
          <%= f.association :ingredient %>
          <%= f.submit "Add ingredient", class: "btn btn-danger", id: "add-ingredient" %>
        <% end %>
      </ul>
    </div>
  </div>
  <hr>
    <div class="row">
    <div class="col-sm-4 col-sm-offset-1">
      <ul class="list-unstyled">
        <li><strong>Add Review</strong></li>
      </ul>
      <hr>
      <%= simple_form_for [ @cocktail, @review ], html: { class: "show-form" } do |f| %>
        <%= f.input :content %>
        <%= f.input :rating, collection: ['1','2','3','4','5'] %>
        <%= f.submit "Add review", class: "btn btn-danger", id: "add-review" %>
      <% end %>
    </div>
    <div class="col-sm-4 col-sm-offset-1">
      <ul class="list-unstyled">
        <li class="review-title">
          <strong>Reviews</strong>
          (<%= @reviews.length %>)
        </li>
        <hr>
        <% unless @reviews.nil? %>
          <% @reviews.each do |review| %>
            <% case review.rating %>
            <% when "1" %>
              <i class="fas fa-star stars"></i><br><br>
              <li>
                <%= review.content %><br><br>
                <%= link_to review_path(review), method: "delete", id: "delete" do %>
                <i class="far fa-trash-alt"></i>
                <% end %>
              </li>
              <hr>
            <% when "2" %>
              <i class="fas fa-star stars"></i><i class="fas fa-star stars"></i><br><br>
              <li>
                <%= review.content %><br><br>
                <%= link_to review_path(review), method: "delete", id: "delete" do %>
                <i class="far fa-trash-alt"></i>
                <% end %>
              </li>
              <hr>
            <% when "3" %>
              <i class="fas fa-star stars"></i><i class="fas fa-star stars"></i><i class="fas fa-star stars"></i><br><br>
              <li>
                <%= review.content %><br><br>
                <%= link_to review_path(review), method: "delete", id: "delete" do %>
                <i class="far fa-trash-alt"></i>
                <% end %>
              </li>
              <hr>
            <% when "4" %>
              <i class="fas fa-star stars"></i><i class="fas fa-star stars"></i><i class="fas fa-star stars"></i><i class="fas fa-star stars"></i><br><br>
              <li>
                <%= review.content %><br><br>
                <%= link_to review_path(review), method: "delete", id: "delete" do %>
                <i class="far fa-trash-alt"></i>
                <% end %>
              </li>
              <hr>
            <% when "5" %>
              <i class="fas fa-star stars"></i><i class="fas fa-star stars"></i><i class="fas fa-star stars"></i><i class="fas fa-star stars"></i><i class="fas fa-star stars"></i><br><br>
              <li>
                <%= review.content %><br><br>
                <%= link_to review_path(review), method: "delete", id: "delete" do %>
                <i class="far fa-trash-alt"></i>
                <% end %>
              </li>
              <hr>
            <% end %>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/doses/new.html.erb
<div class="container">
  <h1>New Ingredient</h1>
  <%= simple_form_for [ @cocktail, @dose ] do |f| %>
    <%= f.input :description %>
    <%= f.association :ingredient %>
    <%= f.submit "Add ingredient", class: "btn btn-primary", id: "add-ingredient" %>
  <% end %>
  <%= link_to 'Back', cocktail_path(@cocktail) %>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag 'logo.jpg' %>
  </a>

  <div class="search">
    <%= form_tag(cocktails_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Cocktails", class: "search-input" %>
      <%= submit_tag "Search", :name => nil, class: "search-button" %>
    <% end %>
  </div>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <a href="/cocktails/new"><span class="element"></span></a>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Host</a></li>
        <li><a href="#">Trips</a></li>
        <li><a href="#">Messagese</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= javascript_pack_tag "application" %>
    <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.9"></script>
  </body>
</html>